### ISSUE TITLE
JS if else

### ISSUE THREAD

**Issue by MrOutput** [Shougo/neosnippet-snippets#104]
looks like the else is indented one too many AND there is no target for the else condition
![1455563760](https://cloud.githubusercontent.com/assets/8491687/13058092/4a584fbc-d3e6-11e5-911f-4798d74d3d64.png)

**Comment by ujihisa** [comment]
Not reproducible for me.

**Comment by MrOutput** [comment]
I am not having the indention issue on some files.. must be a local thing. Anyway, please add a target for the else condition

**Comment by ujihisa** [comment]
Added it.
