### ISSUE TITLE
Delayed expression evaluation

### ISSUE THREAD

**Issue by jreinert** [Shougo/neosnippet-snippets#108]
I'm not sure if i've missed it in the documentation but it seems to me that there's no way for delayed expression evaluation.

see the following example:

```
\section{${1:Section Name}}
\label{${2:sec:`tolower(substitute('$1', '\W', '-', 'g'))`}}  
${0}
```

so if i just stepped through that snippet i'd expect it to evaluate to

``` latex
\section{Section Name}
\label{sec:section-name}
```

Maybe you could check if there are special characters inside the backticks and evaluate only after they've been expanded?

**Comment by Shougo** [comment]
https://github.com/Shougo/neosnippet.vim/issues/270
