### ISSUE TITLE
Different snippet options

### ISSUE THREAD

**Issue by CrashyBang** [Shougo/neosnippet-snippets#120]
I looked around online but could not find any relevant docs.

Could you explain `options` and `abbr` and possibly add a section to the README.

For example why does `options` sometimes have `body` or `head` etc..?

Cheers.

**Comment by Shougo** [comment]
> Could you explain options and abbr and possibly add a section to the README.

Please read the neosnippet documentation.
`:help neosnippet-snippet-syntax`
I don't want to add them to README.  It just waste of the time.

> For example why does options sometimes have body or head etc..?

```
	+ head	This snippet expands at the beginning of a line only.
		Note: This is the same as "prev_word '^'" which is still
		there for backwards compatibility.
```
