### ISSUE TITLE
How to avoid temporary files?

### ISSUE THREAD

**Issue by Vayn** [Shougo/neosnippet-snippets#124]
Hi, I just found there are some temporary (cache) files generated automatically.  Like this:

![screenshot](http://ww2.sinaimg.cn/large/6205603bjw1fagvd51538j209z04tmxg.jpg)

How to make these files to be generated at specific location? Not everywhere else.

**Comment by Shougo** [comment]
`:help g:neosnippet#data_directory`

**Comment by Vayn** [comment]
Thank you :octocat:
