### ISSUE TITLE
Warning when opening blade file

### ISSUE THREAD

**Issue by scottgrayson** [Shougo/neosnippet-snippets#133]
[neosnippet] /Users/Scott/.vim/plugged/neosnippet-snippets/neosnippets/blade.snip:15 is ove
rriding `sec` from /Users/Scott/.vim/plugged/neosnippet-snippets/neosnippets/blade.snip:5
Press ENTER or type command to continue
[neosnippet] Please rename the snippet name or use `delete sec`.
Press ENTER or type command to continue

https://github.com/Shougo/neosnippet-snippets/blob/master/neosnippets/blade.snip#L5-L15

**Comment by Shougo** [comment]
Wow.
It must be fixed...
But which should I remove it?
I don't use blade filetype.  So I don't know it.
