### ISSUE TITLE
Indent to SAME line, not line above

### ISSUE THREAD

**Issue by davidosomething** [Shougo/neosnippet-snippets#134]
e.g. on

```
something:
  |abc()
```

i want to expand a snippet to:

```
something:
    indentedSnippet
    ${0}|
    indentedSnippet
    abc()
```

`options indent` matches line `something:`, I want it to match indent of line `abc()`

**Comment by Shougo** [comment]
It is not neosnippet-snippets issue.
Please create it in neosnippet.

And please create the reproduce ways.
I will test it.
We have not ESP skills.
