### ISSUE TITLE
PHP snippets

### ISSUE THREAD

**Issue by ujihisa** [Shougo/neosnippet-snippets#14]
PHPを普段書いている人への質問がてら提案です。

https://github.com/Shougo/neosnippet-snippets/blob/master/neosnippets/php.snip
- 埋込み型PHP (`<?php`をphpファイルの中に散らばらせて書くスタイルです) はもうモダンな書き方だとほとんど使わないらしいので、そのためのsnippetを一斉削除してもよいかな?
- 古い記法のサポートの廃止。例えば`array()`は2年前に`[]`に置き換えられている。
  snippet array
    $${1:#:arrayName} = array('${2}' => ${3} ${0});
- (snipmate由来と思われる)短いスニペット名をもっとdescriptiveな名前への変更

もし反対意見がなければこっちで実際にsnippet書き換えてみます。
このissueはしばらく開いたままにしてみんなが見れたらいいなあと思います。

// なお、php.snipは旧レポジトリ (neosnippet) を含めて半年くらい更新されていないファイルです。

**Comment by shinokada** [comment]
賛成です。
PHPunit Test のsnippetも一緒に入れてくれればいいですねー。
ちなみにblade のsnippets の PR もしておきました。

**Comment by Shougo** [comment]
私は問題ありません。

**Comment by Shougo** [comment]
これの進捗はいかがですか？
