### ISSUE TITLE
when in insert mode, getting error "[neosnippet] Please rename the snippet name or use 'delete pro'"

### ISSUE THREAD

**Issue by thyeun** [Shougo/neosnippet-snippets#152]
Sorry, i'm new to this, so not sure either it is related with neosnippet or not?

this error appear when i opening csharp (cs) file. meaning here once i'm go into ```Insert mode```
than i get the below error

![screenshot_2018-05-30_02-12-12](https://user-images.githubusercontent.com/1939446/40677263-b5ff9d14-63af-11e8-9b7c-f8b080f867c7.jpg)

**Comment by Shougo** [comment]
I cannot reproduce the error.
I think you have added `prop` snippet.

You should create minimal vimrc.
It is not neosnippet and neosnippet-snippets error.

**Comment by thyeun** [comment]
@Shougo i been remove all the ```prop``` inside file and can't find a ```prop```files but the message still appear.

**Comment by Shougo** [comment]
@thyeun Please upload `:messages` result.
It prints the additional information.
