### ISSUE TITLE
Sample tutorials to learn to make snippets for oneself

### ISSUE THREAD

**Issue by enanajmain** [Shougo/neosnippet-snippets#168]
I've been using Ultisnips as long as I can remember. I didn't use Honza's snippet repository. I watched some videos linked at the repository of Ultisnips and could easily make snippets that I needed. And that way, I knew all of the available ones.

I just today installed neosnippet, because due to python requirement in Ultisnips I've uninstalled it for some time. But the snippet structure is not the same, which is no big deal, if only there were some little documentation. I'm pretty sure there is, only I can't find it.

So, could you point me to a documentation or maybe add some if there isn't one?

**Comment by Shougo** [comment]
Please read `:help neosnippet-snippet-syntax`.
