### ISSUE TITLE
using %uc

### ISSUE THREAD

**Issue by jeffshadap** [Shougo/neosnippet-snippets#184]
```
snippet     opt
abbr        option value
options     head
        <option value="${1:value}">%uc($1)</option>
```
I want to get 
`<option value="test">TEST</option>`

On running the above snippet I got

`			<option value="test">%uc(test)</option>
`

is my syntax correct?

**Comment by Shougo** [comment]
Your syntax is not correct.  `%uc()` is not supported in neosnippet.

**Comment by Shougo** [comment]
Unfortunately neosnippet cannot convert the placeholder value.
I want to add the feature in deoppet.nvim though.

**Comment by jeffshadap** [comment]
Thanks for the prompt reply. And a big Thank you for your awesome Vim plugins.
