### ISSUE TITLE
html snippets `label`

### ISSUE THREAD

**Issue by UncleBill** [Shougo/neosnippet-snippets#51]
[html.snip#L250-L252](https://github.com/Shougo/neosnippet-snippets/blob/master/neosnippets/html.snip#L250-L252)
```
<label>${1}: <input type="${2:TARGET}" /><label>${3}
```
closing tag missing `/`

**Comment by ujihisa** [comment]
Thanks! fixed above now.

**Comment by Shougo** [comment]
:+1:
