### ISSUE TITLE
"path" global snippet incorrectly adds a '/' to the end of filenames

### ISSUE THREAD

**Issue by arecarn** [Shougo/neosnippet-snippets#54]
When you use the path snippet the path of the current file including the file name is inserted. additionally a trailing '/' is also added. It seems like this '/' shouldn't be there.

**Comment by arecarn** [comment]
looks like chaning the regex from 
```
\(\/\/*\|\/*$\)
```
to
```
\/\/*\
```
might be able to fix the problem

**Comment by Shougo** [comment]
I don't find "path" snippet in the repository.
Please tell me.

**Comment by arecarn** [comment]
[here] (https://github.com/Shougo/neosnippet-snippets/blob/a2a952cb3b4e03e28f874bbf49a0ed42bdc12531/neosnippets/_.snip#L32)

**Comment by Shougo** [comment]
I get it.  It is bug.

**Comment by Shougo** [comment]
Fixed.
