### ISSUE TITLE
nested snippet's ${0} will not be jumpped to ,is it a bug? if not we should not use ${0} in  all key words snippets .

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/neosnippet-snippets#89]
for example
i have this two snip
```
snippet str
options word
      String ${0}

```
```
snippet for
   for (${1}){
   ${2:#:test}
}
```
I can not expand str  in the paris of for
```
for_   //_ is cursor 
```
then type tab will get 
```
for (_){   //_ is cursor
}
```
the type into `str` and type tab

```
for (str_){ // _ is curosr
}
```
here you can not expand str 
if i change the first snippet to 
```
snippet str
 String ${1}
```
it will be expand success

**Comment by Shougo** [comment]
It is bug.  Fixed.

**Comment by wsdjeg** [comment]
i have update the latest neosnippet and but still get the same result

**Comment by wsdjeg** [comment]
hi @Shougo still get the same jump error.the ${0} in nested snip will not be jumped to

**Comment by Shougo** [comment]
I cannot reproduce it.
Please create new issue in neosnippet.
And please create minimal .vimrc less than 20 lines.

**Comment by wsdjeg** [comment]
ok
